import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Image from "next/image";
import { InnerHero } from "@/components/InnerHero";
import { PillLink } from "@/components/PillLink";
import { portfolios } from "@/data/site";
export function generateStaticParams() { return portfolios.map((item) => ({ slug: item.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const item = portfolios.find((entry) => entry.slug === slug); return item ? { title: item.name, description: item.description, alternates: { canonical: `/portofolio/${item.slug}` } } : {}; }
export default async function PortfolioDetail({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const item = portfolios.find((entry) => entry.slug === slug); if (!item) notFound(); const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "Product", name: item.name, category: item.category, description: item.description }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Beranda", item: "https://kinaraland.com/" }, { "@type": "ListItem", position: 2, name: "Portofolio", item: "https://kinaraland.com/portofolio" }, { "@type": "ListItem", position: 3, name: item.name, item: `https://kinaraland.com/portofolio/${item.slug}` }] }] }; return <main><InnerHero eyebrow={item.category} title={item.name} intro={item.description} /><section className="project-detail"><div><Image src={item.image} alt={item.name} fill sizes="60vw" /></div><aside><span>LOKASI</span><h2>{item.location}</h2><p>Informasi detail proyek sedang disiapkan. Tim Kinara Land dapat membantu menjelaskan informasi yang telah tersedia dan terverifikasi.</p><PillLink href="/hubungi-kami">Minta Informasi Proyek</PillLink></aside></section><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /></main>; }
